
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

volumes:
  ortest.ibm.cn.com:
  peer0.orgtest.ibm.cn.com:
  peer1.orgtest.ibm.cn.com:
  # peer0.org2.example.com:
  # peer1.org2.example.com:

networks:
  byfn:

services:

  ortest.ibm.cn.com:
    extends:
      file:   base/docker-compose-base.yaml
      service: ortest.ibm.cn.com
    container_name: ortest.ibm.cn.com
    networks:
      - byfn

  peer0.orgtest.ibm.cn.com:
    container_name: peer0.orgtest.ibm.cn.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.orgtest.ibm.cn.com
    networks:
      - byfn

  peer1.orgtest.ibm.cn.com:
    container_name: peer1.orgtest.ibm.cn.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.orgtest.ibm.cn.com
    networks:
      - byfn

  # peer0.org2.example.com:
  #   container_name: peer0.org2.example.com
  #   extends:
  #     file:  base/docker-compose-base.yaml
  #     service: peer0.org2.example.com
  #   networks:
  #     - byfn

  # peer1.org2.example.com:
  #   container_name: peer1.org2.example.com
  #   extends:
  #     file:  base/docker-compose-base.yaml
  #     service: peer1.org2.example.com
  #   networks:
  #     - byfn

  cli:
    container_name: cli
    image: hyperledger/fabric-tools:$IMAGE_TAG
    tty: true
    stdin_open: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      #- CORE_LOGGING_LEVEL=DEBUG
      - CORE_LOGGING_LEVEL=INFO
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.orgtest.ibm.cn.com:7051
      - CORE_PEER_LOCALMSPID=OrgTestMSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/orgtest.ibm.cn.com/peers/peer0.orgtest.ibm.cn.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/orgtest.ibm.cn.com/peers/peer0.orgtest.ibm.cn.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/orgtest.ibm.cn.com/peers/peer0.orgtest.ibm.cn.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/orgtest.ibm.cn.com/users/Admin@orgtest.ibm.cn.com/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
        - /var/run/:/host/var/run/
        - ./../chaincode/:/opt/gopath/src/github.com/chaincode
        - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        - ./scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
        - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    depends_on:
      - ortest.ibm.cn.com
      - peer0.orgtest.ibm.cn.com
      - peer1.orgtest.ibm.cn.com
      # - peer0.org2.example.com
      # - peer1.org2.example.com
    networks:
      - byfn
